### PR TITLE
Does This Work???

### PR DESCRIPTION
**Pull request by youkneekin**
I added more stuff but I think I forgot my previous workflow kek

### CODE REVIEW

**Comment by youkneekin** [comment]
uh yeah i forgot to add them to their own branch im stupid

**Comment by EvanDarwin** [comment]
Fix your conflicts and then I will merge it in.

**Comment by TasoOneAsia** [comment]
Hi there 👋, thanks for collaborating on this open source project!

It appears that you may have some conflicts between your branch and the master branch for this repository. For your changes to be successfully merged, we ask that you resolve these conflicts whenever you may get a chance! Please make sure you are also in compliance with our contribution guidelines that can be found [here](https://devnull-as-a-service.com/). 

Good luck!

**Comment by wowjeeez** [comment]
dead chat

**Comment by youkneekin** [comment]
meh lol

**Pull request closed without merging**
